version: "3.9"

services:
  api:
    build: .
    container_name: house-price-api
    command: python main.py serve --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

  dashboard:
    build: .
    container_name: house-price-dashboard
    command: streamlit run app/streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
